openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths:
  /scheduler/plurk:
    get:
      operationId: SchedulerPlurks_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SchedulerPlurk'
components:
  schemas:
    SchedulerPlurk:
      type: object
      required:
        - id
        - content
        - user_id
        - posted
      properties:
        id:
          type: string
        content:
          type: string
        user_id:
          type: string
        posted:
          type: string
          format: date-time
